### ISSUE TITLE
Read wavefront (.obj) files

### ISSUE THREAD

**Issue by danielschroder** [quenio/INE5420#22]
We need a small parser to read wavefront files and create our objects in the World.

More information about the file format can be found at [wikipedia](https://en.wikipedia.org/wiki/Wavefront_.obj_file).

**Comment by quenio** [comment]
We should probably move this issue to release 1.4, so that we can release 1.3 and upload it to VPL.

**Comment by danielschroder** [comment]
Agreed. Maybe we should break this issue in smaller tasks later. For now, I'm moving it to Release 1.4.

**Comment by quenio** [comment]
Thanks. But you can keep working on it though, so we can have it for release 1.4 :)
