### ISSUE TITLE
Line clipping - Cohen-Sutherland

### ISSUE THREAD

**Issue by danielschroder** [quenio/INE5420#28]
We need to implement the Cohen-Sutherland clipping algorithm.

**Comment by quenio** [comment]
Algorithm:
- Determine the region code for points `a` and `b` of Line.
- Use region code to determine if Line is: totally visible, partially visible or invisible.
- For partially visible lines, calculate the intersection with Window side, for points `a` and `b`. The Window side is chosen based on region code.
- Discard the intersection points outside the Window.
- Use intersection point inside the Window as the new `a` or `b`.
